### PR TITLE
OPENSTACK-2682: add external network mapping for bigip-onboard

### PR DESCRIPTION
**Pull request by zhang-shengping**
This option "external_physical_mappings" is from
f5-openstack-agent.ini.

The original is "f5_external_physical_mappings".

### CODE REVIEW

**Comment by zhang-shengping** [comment]
image

**Comment by zhang-shengping** [comment]
image

**Comment by zhang-shengping** [comment]
https://gitswarm.f5net.com/openstack/f5-openstack-lbaasv2-agent-lite-pipeline/-/pipelines/6108907

**Comment by zh805** [comment]
please update bigip-onboard-cli.md

**Comment by zhang-shengping** [comment]
new PR to this https://github.com/F5Networks/f5-openstack-agent/pull/2004/commits

**Pull request closed without merging**
