### PR TITLE
Stable/newton merging forward mitaka changes.

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux 

Merging forward.

### CODE REVIEW

**Comment by zancas** [comment]
Note this smoke test is running against the `zancas/newton` container.  Success is sufficient to publish a `stable/newton` container.

**Comment by zancas** [comment]
Note I killed smoke test run #56 because the prod container had not yet deployed when it started.

**Comment by zancas** [comment]
retest this please

**Comment by zancas** [comment]
@pjbreaux @ssorenso I used the result of this smoke test to validate rolling a new `agenttestrunner` container, and I pushed a fix to the Jenkinsfile so it points at that container instead of the `mitaka` version.

**Comment by pjbreaux** [comment]
@zancas: The unit tests in this PR are not running. `00:45:31 sudo: py.test: command not found`

We should get this working in this PR, but I also created another issue for unit test failures not reporting a build failure in openstack Jenkins and assigned it to you. That issue should be fixed in liberty and merged forward.

**Comment by zancas** [comment]
retest this please

**Comment by zancas** [comment]
retest this please

**Pull request closed without merging**
