### PR TITLE
Refactor fdb updates

### PR DESCRIPTION
**Pull request by jlongstaf**
@richbrowne 
DO NOT MERGE

#### What issues does this address?
#963 Refactor fdb updates

#### What's this change do?
Changes how fdb add/deletes are done in post_service_network function. Instead of updating each fdb entry indvidually, collects fdb records for all VTEPs (both loadbalancer and member), then updates each tunnel.  This reduces the number of BIG-IP operations from number of VTEPs to number of tunnels.

#### Where should the reviewer start?
network_service.py

#### Any background context?
Number of VTEPs for a single loadbalancer can be in the hundreds, which is the likely performance bottleneck.

### CODE REVIEW

**Comment by pjbreaux** [comment]
@jlongstaf: I'm going to kick this job to test that the agent build on PR is working. This is just a test of that functionality.

**Comment by pjbreaux** [comment]
ok to test

**Comment by pjbreaux** [comment]
@jlongstaf : the config on the smoke tests was wiped when the job was disabled. That is why you see two lines showing up referring to smoke tests above. If we open new pull requests, we should only get one message: 'Running smoke tests on PR'

**Comment by jlongstaf** [comment]
Retest this please

**Pull request merged**
