### PR TITLE
fix unittests in nightly

### LINKED ISSUE #1021: unit test results are not reported in TRTL.

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux 
#### What issues does this address?
Fixes #1021

### CODE REVIEW

**Comment by zancas** [comment]
The "unit" Jenksfile stage is now _only_ run in the case of a particular Jenkins-injected parameter being set.

**Comment by zancas** [comment]
TRTL does not record a build start during the "unit" stage.

**Comment by zancas** [comment]
`unit_test_run_wrapper.sh` is always invoked from the "Jenkinsfile" directory.

**Comment by pjbreaux** [comment]
@zancas: I though we would get this change into master, then cherry-pick the fix back. Is that not feasible right now?

**Pull request merged**
