### PR TITLE
adding 12.1.2 target

### LINKED ISSUE #849: Running tests against BIGIP12.1.2 image
* Details: 
we need to add targets for BIGIP12.1.2 in the makefile and run tests against 12.1.2

#### OpenStack Release
Liberty, Mitaka, Newton

#### Description
<Describe the enhancement request in detail>

* Details: For bugs, fill out the template below.

#### Agent Version
<Fill in the version you have installed, such as 2.0.1>

#### Operating System
<Fill in the host OS of the machine running the agent, such as Centos 7>

#### OpenStack Release
<Fill in the OpenStack release, such as Liberty>

#### Description
<Describe the bug in detail, steps taken prior to encountering the issue, yand a short explanation of you have deployed openstack and F5 agent>

#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

### PR DESCRIPTION
**Pull request by szakeri**
@pjbreaux 
#### What issues does this address?
Fixes #849 

#### What's this change do?
This change will add 12.1.2 target to nightly.

#### Where should the reviewer start?
systest/

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by szakeri** [comment]
retest this please

**Comment by szakeri** [comment]
retest this please

**Comment by szakeri** [comment]
retest this please

**Comment by szakeri** [comment]
retest this please

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by szakeri** [comment]
retest this please

**Comment by szakeri** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Pull request merged**
