### PR TITLE
feature: Add check tool for neutron db and bigip data sync within age…

### PR DESCRIPTION
**Pull request by zhang-shengping**
…nt level.

Use command:

python auditor.py --config-file /etc/neutron/services/f5/f5-openstack-agent.ini
                  --config-file /etc/neutron/neutron.conf
                  --f5-agent 1b4e247d-6c79-4d38-949f-91af99b10b2c

### CODE REVIEW

**Review by zongzw — APPROVED** [review]
lgtm. It's better to have a session for going through the code in details.

**Comment by zhang-shengping** [comment]
> lgtm. It's better to have a session for going through the code in details.

Yes it will be, I also need a performance environment for testing :)

**Comment by zhang-shengping** [comment]
struc

**Comment by zhang-shengping** [comment]
**不支持同时两个 agent/service provider 控制同一对 F5 BigIP HA 机器。**

service_provider_agent

**Pull request closed without merging**
