### PR TITLE
[OPENSTACK-2483]Fix confusing logs to avoid misunderstanding.

### PR DESCRIPTION
**Pull request by zongzw**
@<reviewer_id>
#### What issues does this address?
Fixes #<issueid>
WIP #<issueid>
...

### CODE REVIEW

**Review by zhaoqin-github — CHANGES_REQUESTED** [review]
Do you have an JIRA id?

**Comment by zongzw** [comment]
> Do you have an JIRA id?

Added

**Review by Niklaus-xie — APPROVED** [review]
lgtm

**Comment by zhaoqin-github** [comment]
> > Do you have an JIRA id?
> 
> Added

The JIRA id need to be saved in commit message.

**Review by zhaoqin-github — CHANGES_REQUESTED** [review]
JIRA id need to be saved in commit message

**Comment by zongzw** [comment]
> JIRA id need to be saved in commit message

Added.

**Review by zhaoqin-github — APPROVED** [review]

**Pull request merged**
