### PR TITLE
Fixed an issue where LOG was assigned a function and not a value

### LINKED ISSUE #685: Misconfigured LOG var results in AttributeError: 'function' object has no attribute 'error'
#### OpenStack Release
Newton

#### Agent Version
Master

#### Operating System
Ubuntu 16.04

#### OpenStack Release
Newton

#### Description
While executing certain operations, a traceback can be observed with the following error:

AttributeError: 'function' object has no attribute 'error'

This was found to

2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1214, in _common_service_handler
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     service, traffic_group)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 199, in prep_service_networking
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     self._assure_subnet_snats(assure_bigips, service, subnetinfo)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py", line 564, in _assure_subnet_snats
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     subnetinfo, tenant_id, snats_per_subnet)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/snats.py", line 88, in get_snat_addrs
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     fixed_address_count=1)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/oslo_log/helpers.py", line 48, in wrapper
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     return method(*args, **kwargs)
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/plugin_rpc.py", line 365, in create_port_on_subnet
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     except messaging.MessageDeliveryFailure:
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver AttributeError: 'function' object has no attribute 'error'
2017-05-03 20:08:19.599 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
2017-05-03 20:08:19.600 19220 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -]     _prep_service_networking took 17.02674 secs _common_service_handler /openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1234
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] 'function' object has no attribute 'error'
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver Traceback (most recent call last):
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver   File "/openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py", line 1230, in _common_service_handler
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver     raise error
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver AttributeError: 'function' object has no attribute 'error'
2017-05-03 20:08:19.601 19220 ERROR f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver
2017-05-03 20:08:19.601 19220 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] _update_service_status update_service_status /openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/f5_openstack_agent-9.3.0-py2.7.egg/f5_openstack_agent/lbaasv2/drivers/bigip/icontrol_driver.py:1296
2017-05-03 20:08:19.601 19220 DEBUG f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver [req-6809df5e-c8fd-4bab-980d-98c414d7ae2c 3c16178c83cd4a378b68c4bf50f7807a 62941e875f374220a5f712a01ff271fe - - -] f5_openstack_agent.lbaasv2.drivers.bigip.icontrol_driver.iControlDriver method _update_pool_status called with arguments ([],) {} wrapper /openstack/venvs/neutron-r14.0.0rc2/lib/python2.7/site-packages/oslo_log/helpers.py:47

#### Deployment
OpenStack-Ansible v14 (Newton) w/ 3 infra nodes. HA vCMP on i7800s

### PR DESCRIPTION
**Pull request by busterswt**
@<reviewer_id>
#### What issues does this address?
Fixes #685
...

#### What's this change do?

Properly instantiates LOG object

#### Any background context?

Resolves tracebacks when certain error conditions are met.

### CODE REVIEW

**Comment by dflanigan** [comment]
@busterswt we really appreciate your pull request. But, first, would you fill out our Contributor License Agreement:

http://f5-openstack-docs.readthedocs.io/en/latest/cla_landing.html#cla-landing

The form can be email to : Openstack_CLA@f5.com

Thanks again for your code, 
Dennis

**Comment by busterswt** [comment]
CLA submitted. Thanks!

**Comment by dflanigan** [comment]
@richbrowne , We have a CLA. We can now review and accept this PR. Thanks, Dennis.

**Comment by mattgreene** [comment]
Approved, but checking with the dev team if we want these changes in earlier branches (i.e. liberty, mitaka).

**Comment by mattgreene** [comment]
We think this change should land in liberty and merge downstream.  We'll close this PR and reopen one against liberty, add a unit test and target for the next maintenance release.

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by jlongstaf** [comment]
Closing as fixed by PR #970 which will be merged forward to mitaka, newton, and master branches

**Pull request closed without merging**
