### PR TITLE
OPENSTACK-2701: refactory flat network for refactory other code.

### PR DESCRIPTION
**Pull request by zhang-shengping**

### CODE REVIEW

**Comment by zhang-shengping** [comment]
single trunk and interface:

image

**Comment by zhang-shengping** [comment]
multiple interfaces with mac
image

traffic group MAC
image


image

**Comment by zhang-shengping** [comment]
image

image

image

image

**Comment by zhang-shengping** [comment]
driver side code change: https://github.com/F5Networks/f5-openstack-lbaasv2-driver/pull/1183

**Review by zh805 — DISMISSED** [review]

**Review by zhaoqin-github — APPROVED** [review]

**Pull request merged**
