### PR TITLE
[OPENSTACK-2482]Remove certs and keys for deleted ssl profiles.

### PR DESCRIPTION
**Pull request by zongzw**
@<reviewer_id>
#### What issues does this address?
Fixes #<issueid>
WIP #<issueid>
...

### CODE REVIEW

**Review by zhaoqin-github — CHANGES_REQUESTED** [review]
Do you have an JIRA id?

**Comment by zongzw** [comment]
> Do you have an JIRA id?
Added

**Review by zhaoqin-github — CHANGES_REQUESTED** [review]
JIRA id need to be save in commit message

**Comment by zongzw** [comment]
> JIRA id need to be save in commit message

Added.

**Review by zhaoqin-github — APPROVED** [review]

**Pull request merged**
