### PR TITLE
changing the status of loadbalancer to ONLINE after creation

### LINKED ISSUE #284: Loadbalancer comes up ACTIVE, OFFLINE after creation
* Title: 

Loadbalancer comes up OFFLINE after creation, the expected status is ONLINE.

#### OpenStack Release
Liberty

#### Description
I ran into this problem during running Tempest scenario tests. It tries to create a loadbalancer, listener and pool member. It never get passed loadbalancer creation, since it expects ONLINE status for loadbalancer.

#### Agent Version
Liberty head with the disconnected feature present.

### PR DESCRIPTION
**Pull request by szakeri**
@mattgreene @pjbreaux 

#### What issues does this address?
Fixes #284

#### What's this change do?
It will change the status of loadbalancer to ONLINE after creation.

#### Where should the reviewer start?
icontrol_driver.py file

### CODE REVIEW

**Comment by mattgreene** [comment]
Ok to commit pending successful run of neutronless tests (these are not currently included in nightly regression).  Also waiting for Paul to review.

**Comment by pjbreaux** [comment]
I'm +1, pending successful tests.

**Comment by richbrowne** [comment]
+1 Pending testing results

**Comment by szakeri** [comment]
**test results:**


<class 'f5.bigip.BigIP'>
============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /Users/zakeri/.virtualenvs/agent/bin/python2.7
cachedir: ../../../../.cache
rootdir: /Users/zakeri/f5-openstack-agent, inifile:
plugins: f5-openstack-test-0.2.0, cov-2.3.1, meta-0.1.0a3, symbols-0.1.0a3
collecting ... collected 11 items
pytest-meta: discarded 0 items

test_disconnected_service_creation.py::test_featureoff_withsegid_lb PASSED

========================== 1 passed in 17.28 seconds ===========================

**Comment by szakeri** [comment]
I ran the tests with virtualenv instead of docker and had to do the following changes to make the test work:

diff --git a/test/functional/neutronless/l2adjacent/test_disconnected_service_creation.py b/test/functional/neutronless/l2adjacent/test_disconnected_service_creation.py
index 541bb3b..818fb1b 100644
--- a/test/functional/neutronless/l2adjacent/test_disconnected_service_creation.py
+++ b/test/functional/neutronless/l2adjacent/test_disconnected_service_creation.py
@@ -84,7 +84,7 @@ SEG_DEPENDENT_LB_URIS =\

          u'https://localhost/mgmt/tm/net/self/'
          '~TEST_128a63ef33bc4cf891d684fad58e7f2d'
-         '~local-bigip1-ce69e293-56e7-43b8-b51c-01b91d66af20?ver=11.6.0',
+         '~local-host-10-2-1-4.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20?ver=11.6.0',

          u'https://localhost/mgmt/tm/net/tunnels/tunnel/'
          '~TEST_128a63ef33bc4cf891d684fad58e7f2d'
@@ -187,7 +187,7 @@ def test_featureoff_withsegid_lb(setup_l2adjacent_test, bigip):
     rpc = icontroldriver.plugin_rpc
     print(rpc.method_calls)
     assert rpc.get_port_by_name.call_args_list == [
-        call(port_name=u'local-bigip1-ce69e293-56e7-43b8-b51c-01b91d66af20'),
+        call(port_name=u'local-host-10-2-1-4.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20'),
         call(port_name=u'snat-traffic-group-local-only-'
                        'ce69e293-56e7-43b8-b51c-01b91d66af20_0')
     ]
@@ -212,7 +212,7 @@ def test_withsegid_lb(setup_l2adjacent_test, bigip):
     rpc = icontroldriver.plugin_rpc
     print(rpc.method_calls)
     assert rpc.get_port_by_name.call_args_list == [
-        call(port_name=u'local-bigip1-ce69e293-56e7-43b8-b51c-01b91d66af20'),
+        call(port_name=u'local-host-10-2-1-4.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20'),
         call(port_name=u'snat-traffic-group-local-only-'
                        'ce69e293-56e7-43b8-b51c-01b91d66af20_0')
     ]
@@ -239,7 +239,7 @@ def test_featureoff_withsegid_listener(setup_l2adjacent_test, bigip):
     rpc = icontroldriver.plugin_rpc
     print(rpc.method_calls)
     assert rpc.get_port_by_name.call_args_list == [
-        call(port_name=u'local-bigip1-ce69e293-56e7-43b8-b51c-01b91d66af20'),
+        call(port_name=u'local-host-10-2-1-4.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20'),
         call(port_name=u'snat-traffic-group-local-only-'
                        'ce69e293-56e7-43b8-b51c-01b91d66af20_0')
     ]
@@ -307,7 +307,7 @@ def test_withsegid_listener(setup_l2adjacent_test, bigip):
     rpc = icontroldriver.plugin_rpc
     print(rpc.method_calls)
     assert rpc.get_port_by_name.call_args_list == [
-        call(port_name=u'local-bigip1-ce69e293-56e7-43b8-b51c-01b91d66af20'),
+        call(port_name=u'local-host-10-2-1-4.openstacklocal-ce69e293-56e7-43b8-b51c-01b91d66af20'),
         call(port_name=u'snat-traffic-group-local-only-'
                        'ce69e293-56e7-43b8-b51c-01b91d66af20_0')
     ]

**Pull request merged**
